### ISSUE TITLE
Make the config file, much more helpful

### ISSUE THREAD

**Issue by pspiagicw** [pspiagicw/sinister#4]
Add options like, channel name, tags to a single channel.

Example
```toml
[channel.ltt]
rss = "..."
tags = [ "tech", "info"]

[channel.scottmanley]
rss = "..."
tags = ["info", "science", "space"]
```

Thus more information will be available to the user.
Especially when `status` subcommand is used.
